# Generated by Django 4.2.3 on 2023-08-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('major_id', models.IntegerField()),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('course1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course1_semester', to='base.courses')),
                ('course2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course2_semester', to='base.courses')),
                ('course3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course3_semester', to='base.courses')),
                ('course4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course4_semester', to='base.courses')),
                ('course5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course5_semester', to='base.courses')),
                ('course6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course6_semester', to='base.courses')),
                ('major', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.majors')),
            ],
            options={
                'unique_together': {('semester_id', 'major')},
            },
        ),
    ]
